"use strict";
let favoriteColor = "blue";
console.log(favoriteColor);
favoriteColor = "black";
console.log(favoriteColor);
favoriteColor = "green";
console.log(favoriteColor);
favoriteColor = "yellow";
console.log(favoriteColor);
let firstName = "Rahat";
console.log(firstName);
firstName = "Farhat";
console.log(firstName);
let day = "Thursday";
console.log(day);
day = "Friday";
console.log(day);
let age = 20;
console.log(typeof age);
let ispresent = true;
console.log(typeof ispresent);
let fullName = "Rahat Bano";
console.log(fullName);
let lastName = "Rahat Bano";
console.log(lastName);
let userName = "Rahat";
console.log(userName);
let number = "20";
console.log(number);
const userNumber = 20;
console.log(userNumber == 20);
let Friday = (ispresent);
console.log(Friday);
let Yesterday = "Thursday";
console.log(Yesterday);
/* let age = "twenty";
console.log (age) */
let Saturday = true;
console.log(Saturday);
// let fullName = "Rahat Bano";
// console.log (fullName);
// let favoriteColor = "Black"
// const userName = "Rahat";
/* console.log (userName);
let newColor: string = 'Black';
console.log(newColor);
let newDay: String = 'Monday';
console.log (newDay);
let newName:String = "Sajid";
console.log (newName) */
let newAge = "thirty";
console.log(newAge);
let newColor = "yellow";
console.log(newColor);
